feat(cli): adding option to compile as dll
CMEPW/myph pull request #8
Opened 2023-11-09 15:01 UTC by Alvarwow69

Add new option that allow you to build your payload as a `.dll`

2023-11-11 01:55 UTC, djnnvx requested changes
good work, some stuff is still missing though

dont forget to run `gofmt -w .` to make sure all is formatted properly, thanks

2023-11-11 01:55 UTC, djnnvx commented on cli/parser.go
> +	os.Setenv("CGO_ENABLED", "1")
can you only enable this for dll compilation please ?

2023-11-11 01:55 UTC, djnnvx commented on cli/parser.go
> +	os.Setenv("CC", "x86_64-w64-mingw32-gcc")
same for this, please

2023-11-11 01:55 UTC, djnnvx commented on cli/parser.go
> +		fmt.Println("[*] Compile payload as executable...")
should be `Compiling`

2023-11-11 01:55 UTC, djnnvx commented on cli/parser.go
> +		fmt.Println("[*] Compile payload as dll...")
should be `Compiling`

2023-11-11 01:55 UTC, djnnvx commented on tools/utils.go
> +	export bool,
boolean should have a verb inside the variable name

in this case, i think `shouldExport` is good

2023-11-11 01:55 UTC, djnnvx commented on tools/utils.go
> +	fmt.Println("c'est fait ça marche c'est trop bien")
can you remove this test-code please ?

2023-11-13 09:26 UTC, Alvarwow69 commented
All good

2023-11-13 09:34 UTC, djnnvx approved these changes
good work

2023-11-13 09:34 UTC, merged